### ISSUE TITLE
Updating a short amount of time

### ISSUE THREAD

**Issue by Marcus-Rosti** [Marcus-Rosti/CS_5010_Project#11]
When we update just a short time, there's an issue of it not having granular enough data and just creates a double line.

**Comment by Marcus-Rosti** [comment]
Nathan, mabye you could check to see if the time is < 1 hour and then just return nothing and I'll catch that return on the controller side of things.

**Comment by Marcus-Rosti** [comment]
Hey if you think this is finished you can just close this issue

**Comment by imppilot** [comment]
Can controller catch the zeros?  If so, I'd consider this closed.
