### ISSUE TITLE
Create empty CSV file with header when file does not exist

### ISSUE THREAD

**Issue by nm1291** [Marcus-Rosti/CS_5010_Project#13]
If file does not exist in data folder, create with empty header before update() function is called.

**Comment by Marcus-Rosti** [comment]
I think what I'm going to have controller do is take in a filename from the command line.  If no file is passed in that it will create a new one and write the header. Then call update_weather on that file.

**Comment by nm1291** [comment]
sounds good.

**Comment by Marcus-Rosti** [comment]
Resolved in ecea7c9
