### ISSUE TITLE
Create a startup function

### ISSUE THREAD

**Issue by Marcus-Rosti** [Marcus-Rosti/CS_5010_Project#18]
Create a startup function that initialized a data frame.

**Comment by nm1291** [comment]
Data Frame created. 
Will add a few more additional columns, once the functions are ready
datetime_std
main_temp_F
main_temp_max_F
main_temp_min_F

**Comment by nm1291** [comment]
added few columns to data frame:
datetime_std
date_std
main_temp_F
main_temp_min_F
main_temp_max_F

Feature completed:  95c57b9076f1fc2d5db76c2d077b924b6f8a9012
