### ISSUE TITLE
command line with argument passed (SampleCSV.csv) does not seem to work.

### ISSUE THREAD

**Issue by nm1291** [Marcus-Rosti/CS_5010_Project#19]
![image](https://cloud.githubusercontent.com/assets/1998614/9118693/3e1310c2-3c40-11e5-8756-146866b2d7c6.png)

it seems to ignore this and fetch data from beginning.

![image](https://cloud.githubusercontent.com/assets/1998614/9119581/5cb82e9a-3c45-11e5-8b42-d542f13745a8.png)

**Comment by Marcus-Rosti** [comment]
you need to use -i I believe

**Comment by Marcus-Rosti** [comment]
so `python controller.py -i ../data/sampleCSV.csv`

**Comment by Marcus-Rosti** [comment]
Did that work?

**Comment by nm1291** [comment]
Yes that works!  Didn't notice the "-i", my bad.
