### ISSUE TITLE
Pandas column names have a space in front of them

### ISSUE THREAD

**Issue by imppilot** [Marcus-Rosti/CS_5010_Project#20]
This is easy to get around once you realize what's going on, but seems like an issue that should be fixed.

**Comment by nm1291** [comment]
This can easily be done in start_up() function while reading the csv. But I think its better if we just remove the space while we are hardcoding them into the file itself. 

I've done the latter. 

This issue is fixed with 6ae00167fcf6b9f578aa2a85ba40c1a892371080
