### ISSUE TITLE
Today's weather averaging over entire data instead of today.

### ISSUE THREAD

**Issue by nm1291** [Marcus-Rosti/CS_5010_Project#21]
Hey Feiyin, just raising this so we can keep track of our bugs, close this once this is fixed.

**Comment by nm1291** [comment]
WEATHER_DATA['date_std'] has the date part of the timestamp. We could try to use this to get the subset.

**Comment by Marcus-Rosti** [comment]
I'm trying to figure out how to get midnight of last night and I'm not having much luck. 
  My idea then is to use that to subset the dataframe and then use that for all the calculations int today_weather()

**Comment by nm1291** [comment]
Simple...
new_data = WEATHER_DATA[WEATHER_DATA['date_std'] == '01/02/2015']

**Comment by Marcus-Rosti** [comment]
yeah but I was trying to figure out how to get today programmatically

**Comment by nm1291** [comment]
import time
unix_to_date(time.time())

**Comment by Marcus-Rosti** [comment]
Resolved with 8fa255e38b8568264ec290451c4f5a9a63eb0b30
