### ISSUE TITLE
Save graphs as PNG / JPEG option

### ISSUE THREAD

**Issue by nm1291** [Marcus-Rosti/CS_5010_Project#23]
If possible, could you look into saving the graphs as an image on disk. 

This is just to fulfill one of the project requirements Nada specified:
"Capture the results of the queries appropriately (either write results to a file, or store into another data structure, or do something else with the results as appropriate based on your project scenario)"

**Comment by imppilot** [comment]
That's actually somewhat difficult.  From my understanding, you're given one output, and you can either send it to the screen or the disk, but not both.  However, on the window that pops up on screen has a save button which creates a jpeg.

**Comment by imppilot** [comment]
I was mixing python up with another programming language.  Turns out this is actually really easy to do.
