### ISSUE TITLE
Errors when I chose options

### ISSUE THREAD

**Issue by feiyinwu** [Marcus-Rosti/CS_5010_Project#24]
I keep getting this error for every option I chose.

TypeError: 'NoneType' object is not subscriptable

Also everytime I update, the SampleCSV.csv would have an unusual line that contains extra variables. This seems to cause the errors when I chose options. But since it happens every time I run user_interface.py, I can't really get rid of it.

Any idea how I can fix this? Can't view anything now.

**Comment by Marcus-Rosti** [comment]
I think this is mostly due to using Spyder rather than the command line or it has something to due with git updates.  Although I can't be sure without seeing what you have.

**Comment by imppilot** [comment]
I ran into this.  If you run the ui library, WEATHER_DATA gets wiped out.  You have to read it in from the file again.
