### ISSUE TITLE
Create a gui

### ISSUE THREAD

**Issue by Marcus-Rosti** [Marcus-Rosti/CS_5010_Project#4]
This could be out of scope but it would be cool to maybe have a GUI that let's people query information

**Comment by Marcus-Rosti** [comment]
This isn't going to happen.

**Comment by nm1291** [comment]
There is this library called tkinter, and there seems to be quite a lot of tutorials for it. http://www.tutorialspoint.com/python/python_gui_programming.htm

But yea, lack of time. Do you think we can whip up something quick??

**Comment by Marcus-Rosti** [comment]
I can look into it but no promises.
